---
- shell: dpkg-query -W 'php7.1'
  ignore_errors: true
  register: is_php_installed

- name: Remove all existing PHP packages
  become: true
  apt: pkg=php7* autoremove=yes purge=yes state=absent force=yes
  when: is_php_installed|failed

- name: Add repository for Ubuntu
  become: true
  apt_repository: repo={{ php_ppa }}

- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install PHP Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items: "{{ php_packages }}"
  when: php_packages is defined
  notify:
    - restart php7-fpm
    - restart nginx

- include: configure.yml
