---
- name: restart nginx
  become: true
  service: name=nginx enabled=yes state=restarted
  listen: restart app-php

- name: restart php-fpm
  become: true
  service: name=php7.1-fpm enabled=yes state=restarted
  listen: restart app-php
