---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Add Percona apt signing key
  become: true
  apt_key: keyserver=keys.gnupg.net id=8507EFA5 state=present

- name: Add Percona repository
  become: true
  apt_repository: repo='deb http://repo.percona.com/apt xenial main' state=present

- name: Add Percona source repository
  become: true
  apt_repository: repo='deb-src http://repo.percona.com/apt xenial main' state=present

- name: Update apt cache
  become: true
  apt: update_cache=true

- name: Install python packages (required for ansible)
  become: true
  apt: pkg={{ item }} state=present
  with_items:
    - vim
    - python-pycurl
    - python-mysqldb

- name: Install Percona packages
  become: true
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - percona-server-common-5.7
    - percona-server-client-5.7
    - percona-server-server-5.7
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: MySQL | Insure daemon is running correctly
  systemd: name=mysql state=started enabled=yes

- name: MySQL | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: MySQL | Create default configuration template
  template: src=mysqld.conf.j2 dest=/etc/mysql/percona-server.conf.d/mysqld.cnf owner=root group=root mode=0644
  notify: mysql restart

- include: dump-import.yml
