---
- name: Update apt
  become: true
  apt: update_cache=yes

- name: Make sure aptitude is installed
  become: true
  apt: pkg=aptitude state=latest

- name: Update all packages to the latest version
  become: true
  apt: upgrade=yes

- name: Install System Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items: "{{ server_packages }}"
  when: server_packages is defined

- name: Configure the timezone
  become: true
  template: src=timezone.j2 dest=/etc/timezone

- name: More Configure the timezone
  become: true
  file: src=/usr/share/zoneinfo/{{server_timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{ server_locale }}
  become: true

- name: Set default system language vars
  become: true
  lineinfile:
    dest: /etc/default/locale
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^LANG\b", line: "LANG={{ server_locale }}" }
    - { regexp: "^LANGUAGE\b", line: "LANGUAGE={{ server_locale }}" }
    - { regexp: "^LC_ALL\b", line: "LC_ALL={{ server_locale }}" }

- name: Set default GIT editor
  shell: git config --global core.editor vim

- include: cachefilesd.yml
